name: tests

on:
  push:

jobs:
  tests:
    name: Tests (${{matrix.php}}, ${{ matrix.os }}, ${{ matrix.stability }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.4'
        os:
          - 'ubuntu-24.04'
          - 'ubuntu-22.04'
          - 'ubuntu-20.04'
          - 'windows-2022'
          - 'windows-2019'
          - 'macos-13'
          - 'macos-14'
          - 'macos-15'
        stability:
          - 'prefer-stable'
    steps:
      - name: Set Git To Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl
          ini-values: "memory_limit=-1"
      - name: Validate Composer
        run: composer validate
      - name: Install Dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress
      - name: Execute Tests
        run: composer test
